CROSS_COMPILE ?=

ifdef CROSS_COMPILE
    CC := $(CROSS_COMPILE)gcc
else
    CC := gcc
endif

TARGET = writer
SRC = writer.c

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)
